# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mehbubul Hasan Al-Quvi
title: Researcher | Prospective Grad Student | Engineer
email: quvi007 [at] gmail [dot] com
# email_title: 
# phone: +88 01877828385
# phone_title: Phone (Phone title override)
# website: quvi007.github.io
# website_title: Web (Website title override)
# cv: tareqmahmood.xyz/files/tareq_cv.pdf
# cv_title: Curriculum vitae

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  quvi007
stackoverflow_username: ""
linkedin_username: quvi007

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/quvi.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, <b>Quvi</b> here. 
  I am a remote research intern at OrderLab, 
  <a href="https://www.umich.edu/">University of Michigan, Ann Arbor</a>. 
  My research interests lie in the intersection of Operating Systems, Computer Architecture and Compilers. 
  My current research focuses on reliable kernel extensibility.
  
content:
  - title: Research Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Yiming Xiang, Wanning He, Mehbubul Hasan Al-Quvi, and Peng Huang
        link: 
        link_text: <mark>Paper Link</mark>
        caption: 19th USENIX Symposium on Operating Systems Design and Implementation (OSDI 2025) - CORE Rank <b>A*</b> - Acceptance Rate 19%
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            ePass: A Framework for Enhancing Flexibility and Runtime Safety of eBPF Programs
          </b></h4><br>

          <p style="text-align: center">
            <img align="center" src="images/eBPF.png" alt="eBPF" height="300"/>
            <img align="center" src="images/ePass.png" alt="ePass" height="300"/>
            <br>
            <img align="center" src="images/ePass_CORE.png" alt="ePass_CORE" height="300"/>
            <img align="center" src="images/ePass_Transformation.png" alt="ePass_Transformation" height="300"/>
          </p>

          <details>
          <summary><p>⮞ Details</p></summary>
          <p>
          eBPF has become a popular technology for extending the Linux kernel.
          </p>
          </details>

      - layout: left
        sub_title: Mehbubul Hasan Al-Quvi, Shamit Fatin, Sukarna Barua, and Anindya Iqbal
        link: 
        link_text: <mark>Paper Link</mark>
        # quote: 
        #   Mehbubul Hasan Al-Quvi, Shamit Fatin, Sukarna Barua, and Anindya Iqbal
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            LELANTE: LEveraging LLM for Automated ANdroid Test Execution
          </b></h4><br>

          <p style="text-align: center">
            <img align="center" src="images/LELANTE_EXEC.png" alt="LELANTE_EXEC" height="300"/>
          </p>

          <details>
          <summary><p>⮞ Details</p></summary>
          <p>
          </p>
          </details>

      - layout: left
        sub_title: H.A.Z. Sameen Shahgir, Mehbubul Hasan Al-Quvi, Shamit Fatin, Sukarna Barua, and Anindya Iqbal
        link: 
        link_text: <mark>Paper Link</mark>
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            DistilAgent: Distilling Agentic Capabilities from Large Language Models for Long-Horizon UI Navigation
          </b></h4><br>

          <p style="text-align: center">
            <img align="center" src="images/LELANTE_EXEC.png" alt="LELANTE_EXEC" height="300"/>
          </p>

          <details>
          <summary><p>⮞ Details</p></summary>
          <p>
          </p>
          </details>

      - layout: left
        sub_title: Mehbubul Hasan Al-Quvi, Aszad Rakin, Md Saqib Hasan, and Muhammad Abdullah Adnan
        caption: 
        link: 
        link_text: <mark>Paper Link</mark>

        # quote: 
        #   Mehbubul Hasan Al-Quvi, Aszad Rakin, Md Saqib Hasan, and Muhammad Abdullah Adnan
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            
          </b></h4><br>

          <p style="text-align: center">
            <img align="center" src="images/mtul.png" alt="MTUL" height="200"/>
          </p>

          <details>
          <summary><p>⮞ Details</p></summary>
          <p>
          Trajectory User Linking (TUL) is the problem of identifying the user 
          (i.e., his identity) from the trajectories generated by him. 
          Existing works on TUL leverage a single trajectory for identifying a user. 
          We propose a novel problem called Multi-Trajectory User Linking (MTUL), 
          which leverages all available trajectories generated by a particular user 
          to identify him. Thus, MTUL is essentially the generalized TUL problem. 
          This problem has significant applications in Location-Based Services 
          (LBSs) such as personalized route planning and point-of-interests (POI) 
          recommendation, movement anomaly detection, etc. 
          We provide an end-to-end solution to the MTUL problem using 
          sequence embedding and GRU and achieve reasonable accuracy by taking into 
          account the POI type and region information. 
          We consider this work to be an important addition to the TUL research.  
          </p>
          </details>

      - layout: left
        # title: Recognition of Bengali Handwritten Digits Using Convolutional Neural Network Architectures
        sub_title: Md. Mahmudul Hasan, Md. Rafid UI Islam, and Md. Tareq Mahmood
        caption: International Conference on Bangla Speech and Language Processing (ICBSLP 2018)
        link: https://doi.org/10.1109/ICBSLP.2018.8554753
        link_text: <mark>Paper Link</mark>
        # quote: 
        #   Md. Mahmudul Hasan, Md. Rafid UI Islam, and Md. Tareq Mahmood
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            Recognition of Bengali Handwritten Digits Using Convolutional Neural Network Architectures
          </b></h4><br>

          <p style="text-align: center">
            <img align="center" src="images/bangla-digit-recognition.png" alt="bangla-digit-recognition" height="200"/>
          </p>

          <details>
          <summary><p>⮞ Details</p></summary>
          <p>
          Handwritten digit recognition has been the “hello world” of deep learning. 
          Yet, there are no significant work on Bengali handwritten digits due to a 
          lack of benchmark dataset. NumtaDB is the largest dataset on Bengali handwritten 
          digits and currently we have the best accuracy of 99.3359% on it. We used popular 
          CNN architectures namely, ResNet34 and Resnet50. We preprocessed the data, used data 
          augmentation, and trained our models with augmented data. We tested our models on 
          both the raw test data and cleaned test data. We found that slightly underfitted 
          models work better on the test data. And finally ensembled our six best models to 
          get our final predictions. In this paper we describe some methods and techniques that 
          performs well in NumtaDB dataset.  
          </p>
          </details>

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Systems Research Intern
        caption: June 2024 - Present
        link: https://orderlab.io
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Department of Computer Science and Engineering

          University of Michigan, Ann Arbor
      
      - layout: left
        title: Systems Researcher
        caption: January 2025 - Present
        link: https://cse.buet.ac.bd
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          EDGE Research Laboratory (EdgeLab@BUET)

          [http://edgelab.buet.io](http://edgelab.buet.io)

      - layout: left
        title: Research Assistant
        caption: February 2024 - December 2024
        link: https://cse.buet.ac.bd
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          SAMSUNG Applied Machine Learning Research Laboratory (SRBDLab@BUET)

          [http://srbd.buet.io](http://srbd.buet.io)

  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Science 
        # sub_title: Lecturer
        caption: April 2019 - July 2024
        # link: https://buet.ac.bd
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Computer Science and Engineering

          Bangladesh University of Engineering and Technology 

          CGPA: **3.84 out of 4.00**

          Thesis: *Analyzing Large Language Models in Low-Resource Settings*
          

  - title: Grants and Fellowships
    layout: text
    content: | # this will include new lines to allow paragraphs
      * Selected for High Profile ICT Scholar Fellowship 2018-19
      * Received ICT Innovation Fund 2018-19 (with Kazi Antor Hasan)


  - title: Awards and Honors
    layout: text
    content: | # this will include new lines to allow paragraphs
      * Runner Up Student Poster Award - NSysS, 2018
      * Best Student Paper Award - ICBSLP, 2018 
      * Champion Team (BUET Backpropers), NumtaDB Computer Vision Challenge - Bengali.Ai, 2018
      * Best Kernel, NumtaDB Computer Vision Challenge - Bengali.Ai, 2018
      * Honourable Mentioned Team (BUET Backpropers), Machine Learning Challenge - National Robotic Festival, 2017
      * Champion Team (BUET Resonance) - Battle of Speed, LFR Challenge, 2015
      * 2nd Placed Team (BUET Novices) - Intra-BUET Programming Contest, 2015

  - title: News
    layout: text
    content: | # this will include new lines to allow paragraphs
      * **[Jun 2024]** Started as a Remote Research Intern at OrderLab, U-M.
      * **[Jun 2024]** Defended my Bachelor's thesis. Thanks to my supervisor.
      * **[Jun 2022]** PathOracle accepted in ECML-PKDD 2022.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my spare time, I like to try new frameworks, languages and linux distros. 
      I love to build small apps/software/scripts for my own use.
      
      My Erdős number is 4. 
      Paul Erdős - Ronald L. Graham - Jeffrey D. Ullman - Timos K. Sellis - Me.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
